---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-firewalld
      firewalld_allow_services:
        - {service: "http"}
      firewalld_allow_ports:
        - {port: "4444/tcp"}
      firewalld_filter_sources:
        - {source: "127.0.0.1", port: "80"}
